### ISSUE TITLE
Error On Initialization

### ISSUE THREAD

**Issue by dinosaw** [daeks/twitchbot#1]
Hello,

I'm having a problem running your bot. After configuring the config.example.php and renaming it to config.php, and also after permitting write permissions to the directory, I then try and launch the bot by `php -f twitchbot.php`, however I am greeted with the following error:

```
PHP Parse error:  syntax error, unexpected '[' in /home/user/twitchbot/twitchbot.php on line 117
```

When I check line 117 on twtchbot.php, this is the line of code:

```
            $this->username = explode('!', ltrim($this->data[0], ':'))[0];
```

Any idea what could be happening?

**Comment by daeks** [comment]
hi which php version are you using? you could check logs directory and post its content here (without the passwd)
